object BuildDependenciesVersions {
    const val GRADLE_ANDROID_VERSION = "7.0.3"
    const val KOTLIN_VERSION = "1.6.10"
    const val COMPOSE_COMPILER_VERSION = "1.1.0"
    const val COMPOSE_UI_VERSION = "1.1.0"
    const val COMPOSE_ACTIVITY_VERSION = "1.5.1"
    const val NAVIGATION_VERSION = "2.3.5"
    const val CORE_KTX_VERSION = "1.7.0"
    const val APPCOMPAT_VERSION = "1.4.1"
    const val MATERIAL_DESIGN_VERSION = "1.6.1"
    const val MOSHI_VERSION = "1.11.0"
    const val RETROFIT_VERSION = "2.9.0"
    const val OKHTTP_VERSION = "4.10.0"
    const val ROOM_VERSION = "2.4.1"
    const val KOTLINX_COROUTINES_VERSION = "1.3.9"
    const val HILT_VERSION = "2.40"
    const val TIMBER_VERSION = "4.7.1"

    // Tests
    const val TEST_VERSION = "1.3.0"
    const val EXT_VERSION = "1.1.2"
    const val ARCH_CORE_VERSION = "2.1.0"
    const val JUNIT_VERSION = "4.13.1"
    const val MOCKITO_VERSION = "2.23.0"
    const val ESPRESSO_VERSION = "3.3.0"
}